# Generated by Django 4.1.2 on 2022-11-03 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_of_day', models.CharField(choices=[('day', 'Дневной'), ('night', 'Ночной')], max_length=10, null=True, verbose_name='Вид')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('current', models.BooleanField(default=True, verbose_name='Действующий')),
                ('canceled', models.BooleanField(default=False, verbose_name='Аннулирован')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуски',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('register_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='ГРН')),
                ('vin', models.CharField(blank=True, max_length=20, null=True, verbose_name='VIN')),
                ('sts', models.CharField(blank=True, max_length=10, null=True, verbose_name='СТС')),
                ('sts_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи СТС')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=20, null=True, verbose_name='Модель')),
                ('created', models.DateField(blank=True, null=True, verbose_name='Дата выпуска ТС')),
                ('eco_class', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Экологический класс')),
                ('max_weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Разрешенная максимальная масса')),
                ('weight_without_load', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Масса без нагрузки')),
                ('number_check_card', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер диагностической карты')),
                ('date_check_card', models.DateField(blank=True, null=True, verbose_name='Срок действия диагностической карты')),
                ('date_extended_pass_year', models.DateField(blank=True, null=True, verbose_name='Можно продлить годовой пропуск')),
                ('date_extended_pass_one_time', models.DateField(blank=True, null=True, verbose_name='Можно продлить разовый пропуск')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='PassYear',
            fields=[
                ('pass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pass')),
                ('title', models.CharField(blank=True, default='Годовой пропуск', max_length=20)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_passes', to='main.car', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Годовой пропуск',
                'verbose_name_plural': 'Годовые пропуски',
            },
            bases=('main.pass',),
        ),
        migrations.CreateModel(
            name='PassOneTime',
            fields=[
                ('pass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pass')),
                ('title', models.CharField(blank=True, default='Разовый пропуск', max_length=20)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_time_passes', to='main.car', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Разовый пропуск',
                'verbose_name_plural': 'Разовые пропуски',
            },
            bases=('main.pass',),
        ),
    ]
