# Generated by Django 4.1.2 on 2022-10-20 12:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('register_number', models.CharField(blank=True, max_length=10, null=True)),
                ('vin', models.CharField(blank=True, max_length=20, null=True)),
                ('sts', models.CharField(blank=True, max_length=10, null=True)),
                ('sts_date', models.DateTimeField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('eco_class', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_without_load', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_check_card', models.CharField(blank=True, max_length=20, null=True)),
                ('date_check_card', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_of_day', models.CharField(choices=[('day', 'day'), ('night', 'night')], max_length=10)),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 12, 16, 50, 792671, tzinfo=datetime.timezone.utc))),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('can_be_used', models.DateTimeField(blank=True, null=True)),
                ('current', models.BooleanField(default=True, verbose_name='Действующий')),
                ('canceled', models.BooleanField(default=False, verbose_name='Аннулирован')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='main.car')),
            ],
        ),
        migrations.CreateModel(
            name='PassTenDays',
            fields=[
                ('pass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pass')),
            ],
            bases=('main.pass', models.Model),
        ),
        migrations.CreateModel(
            name='PassYear',
            fields=[
                ('pass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pass')),
            ],
            bases=('main.pass', models.Model),
        ),
    ]
