# Generated by Django 4.1.2 on 2022-10-20 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='passtendays',
            options={'verbose_name': 'Разовый пропуск', 'verbose_name_plural': 'Разовые пропуски'},
        ),
        migrations.AlterModelOptions(
            name='passyear',
            options={'verbose_name': 'Годовой пропуск', 'verbose_name_plural': 'Годовые пропуски'},
        ),
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_check_card',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='sts_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='can_be_used',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='start',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 20)),
        ),
    ]
