# Generated by Django 4.1.2 on 2022-11-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='date_extended_pass_year',
        ),
        migrations.AddField(
            model_name='car',
            name='date_extended_pass_year_day',
            field=models.DateField(blank=True, null=True, verbose_name='Можно продлить годовой дневной пропуск'),
        ),
        migrations.AddField(
            model_name='car',
            name='date_extended_pass_year_night',
            field=models.DateField(blank=True, null=True, verbose_name='Можно продлить годовой ночной пропуск'),
        ),
    ]
