# Generated by Django 4.1.2 on 2022-11-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_car_date_extended_pass_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='noname', max_length=50, verbose_name='Имя')),
                ('contacts', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакты')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Инофрмация')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='main.owner', verbose_name='Владелец ТС'),
        ),
    ]
