# Generated by Django 4.1.2 on 2022-10-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_options_alter_passtendays_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='car',
        ),
        migrations.AddField(
            model_name='passtendays',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pass_ten_days', to='main.car'),
        ),
        migrations.AddField(
            model_name='passyear',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pass_year', to='main.car'),
        ),
    ]
