# Generated by Django 4.1.2 on 2022-11-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_owner_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='can_extended_pass_one_time',
            field=models.BooleanField(blank=True, default=False, verbose_name='Можно продлить разовый'),
        ),
        migrations.AddField(
            model_name='car',
            name='can_extended_pass_year_day',
            field=models.BooleanField(blank=True, default=False, verbose_name='Можно продлить годовой дневной'),
        ),
        migrations.AddField(
            model_name='car',
            name='can_extended_pass_year_night',
            field=models.BooleanField(blank=True, default=False, verbose_name='Можно продлить годовой ночной'),
        ),
        migrations.AddField(
            model_name='car',
            name='date_can_extended_pass_one_time',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи заявки на разовый'),
        ),
        migrations.AddField(
            model_name='car',
            name='date_can_extended_pass_year_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи заявки на годовой дневной'),
        ),
        migrations.AddField(
            model_name='car',
            name='date_can_extended_pass_year_night',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи заявки на годовой ночной'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_extended_pass_one_time',
            field=models.DateField(blank=True, null=True, verbose_name='Можно продлить разовый'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_extended_pass_year_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата продления годового дневного'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_extended_pass_year_night',
            field=models.DateField(blank=True, null=True, verbose_name='Дата продления годового ночного'),
        ),
    ]
