# Generated by Django 4.1.2 on 2022-11-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car_can_extended_pass_one_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='can_extended_pass_one_time',
            new_name='can_update_pass_one_time',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='can_extended_pass_year_day',
            new_name='can_update_pass_year_day',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='can_extended_pass_year_night',
            new_name='can_update_pass_year_night',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='date_extended_pass_one_time',
            new_name='date_new_pass_one_time',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='date_extended_pass_year_day',
            new_name='date_new_pass_year_day',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='date_extended_pass_year_night',
            new_name='date_new_pass_year_night',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='date_can_extended_pass_one_time',
            new_name='date_of_application_pass_one_time',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='date_can_extended_pass_year_day',
            new_name='date_of_application_pass_year_day',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='date_can_extended_pass_year_night',
            new_name='date_of_application_pass_year_night',
        ),
    ]
