# Generated by Django 4.1.2 on 2022-11-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_can_extended_pass_one_time_car_can_update_pass_one_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='requested_pass_one_time',
            field=models.BooleanField(blank=True, default=False, verbose_name='Подал заявку на разовый'),
        ),
        migrations.AddField(
            model_name='car',
            name='requested_year_day_pass',
            field=models.BooleanField(blank=True, default=False, verbose_name='Подал заявку на годовой дневной'),
        ),
        migrations.AddField(
            model_name='car',
            name='requested_year_night_pass',
            field=models.BooleanField(blank=True, default=False, verbose_name='Подал заявку на годовой ночной'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
